        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 10 15:20:25 2016
        MODULE INIT_RANDOM_SEED__genmod
          INTERFACE 
            SUBROUTINE INIT_RANDOM_SEED
            END SUBROUTINE INIT_RANDOM_SEED
          END INTERFACE 
        END MODULE INIT_RANDOM_SEED__genmod
